version: '3'
services:
  go-starter:
    image: purposeinplay/go-starter
    container_name: go-starter
    build:
      context: ../
      dockerfile: ./d8t/Dockerfile.dev
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      SERVER_TYPE: http
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12.3-alpine
    container_name: go-starter-db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gostarter
      POSTGRES_PASSWORD: gostarter
      POSTGRES_DB: gostarter
    ports:
      - 4433:5432